# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: local
    hooks:
    -   id: sort-imports
        name: sort imports
        entry: ./sort_imports.sh
        language: system
        files: ^lib/
-   repo: https://github.com/dluksza/flutter-analyze-pre-commit
    rev: "0bfdb7415bb2d02794a884bf2b763a92772001eb"
    hooks:
    -   id: flutter-analyze

