name: habitquokka
description: Strength or growth good habits with additional motivation to discover images hidden behind closed windows.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: 2.0.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
