name: habitquokka
description: Strength or growth good habits with additional motivation to discover images hidden behind closed windows.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: 2.0.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  async_redux:
  equatable:
  copy_with_extension: ^2.0.0-nullsafety.1
  supercharged:
  beamer: ^1.0.0-nullsafety.0

  # UI
  cached_network_image: ^3.0.0-nullsafety
  flex_color_scheme: ^2.0.0-nullsafety.1
  flutter_screenutil: ^5.0.0-nullsafety.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  import_sorter: ^4.4.1
  pedantic:
  copy_with_extension_gen: ^2.0.0-nullsafety.1
  intl_utils:

dependency_overrides:
  analyzer: ^1.0.0
  yaml: ^3.0.0
  args: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/blobs/

flutter_intl:
  enabled: true
  class_name: L10n

import_sorter:
  comments: false
  ignored_files:
    - /lib/generated
