name: habitquokka
description: Strength or growth good habits with additional motivation to discover images hidden behind closed windows.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: 2.0.0

dependencies:
  flutter:
    sdk: flutter
  async_redux:
  equatable:
  copy_with_extension: ^2.0.0-nullsafety.1
  supercharged:

  # UI
  cached_network_image: ^3.0.0-nullsafety
  flex_color_scheme: ^2.0.0-nullsafety.1
  flutter_screenutil: ^5.0.0-nullsafety.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  import_sorter:
  pedantic:
  copy_with_extension_gen: ^2.0.0-nullsafety.1

flutter:
  uses-material-design: true


import_sorter:
  comments: false
  ignored_files:
    - /lib/generated
